# Generated by Django 4.1.2 on 2022-10-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_familiar_delete_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='familiar',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
