# Generated by Django 4.1.2 on 2022-11-12 14:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avanzado', '0002_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
